version: "3"
services:
  web:
    platform: linux/x86_64 # M1チップ対応のため追記
    container_name: imweb_web
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    tty: true
    depends_on:
      - app
  app:
    platform: linux/x86_64 # M1チップ対応のため追記
    container_name: imweb_app
    build:
      context: ./.docker/node
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3333:3333"
