version: "3.7"

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./../next-ts
        target: /app
    ports:
      - "3333:3333"